export const publications = [
  {
    slug: 'how-satellites-strengthen-socially-sustainable-supply-chain-governance',
    type: 'journal',
    year: 2026,
    title: 'How satellites strengthen socially sustainable supply chain governance',
    authors: ['Alessandro Paravano'],
    venue: 'Production Planning & Control',
    details: 'Published online 8 July 2026',
    doi: '10.1080/09537287.2026.2695694',
    publisherUrl: 'https://www.tandfonline.com/doi/full/10.1080/09537287.2026.2695694',
    repositoryUrl: null,
    repositoryLabel: null,
    fullPage: false,
    themes: ['Earth Observation', 'Supply Chain Governance', 'Social Sustainability', 'AI']
  },
  {
    slug: 'co2-real-options-offshore-energy-infrastructure',
    type: 'journal',
    year: 2026,
    title: 'A Novel CO₂-Based Real-Options Methodology to Integrate Uncertainty and Flexibility in Infrastructure Appraisal: An Illustrative Application in Offshore Energy Infrastructure',
    authors: ['Alessandro Paravano', 'Alessandra Neri', 'Gregorio Brizzante', 'Alessandro Bosani', 'Enrico Cagno', 'Giorgio Locatelli'],
    venue: 'IEEE Transactions on Engineering Management',
    details: 'Vol. 73 · pp. 3881–3895',
    doi: '10.1109/TEM.2026.3697823',
    publisherUrl: 'https://ieeexplore.ieee.org/document/11561058/',
    repositoryUrl: null,
    repositoryLabel: null,
    fullPage: false,
    themes: ['Infrastructure Appraisal', 'Real Options', 'Uncertainty', 'Energy Infrastructure']
  },
  {
    slug: 'small-change-or-big-bang-new-space-project-planning',
    type: 'journal',
    year: 2026,
    title: 'Small change or big bang? The shift from legacy to new space project planning',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'Acta Astronautica',
    details: 'Vol. 249, Part A · pp. 482–490 · online 2026',
    doi: '10.1016/j.actaastro.2026.07.011',
    publisherUrl: 'https://www.sciencedirect.com/science/article/pii/S0094576526004637',
    repositoryUrl: null,
    repositoryLabel: null,
    fullPage: false,
    themes: ['New Space Economy', 'Project Planning', 'Project Governance', 'Value']
  },
  {
    slug: 'co2-real-options-nuclear-power-plants',
    type: 'journal',
    year: 2026,
    title: 'A CO₂-based real options model for assessing the impact of external events on nuclear power plants',
    authors: ['Alessandro Paravano', 'Giacomo Galeotti', 'Alessandra Neri', 'Enrico Cagno', 'Giorgio Locatelli'],
    venue: 'Nuclear Engineering and Design',
    details: 'Vol. 448 · Article 114692',
    doi: '10.1016/j.nucengdes.2025.114692',
    publisherUrl: 'https://www.sciencedirect.com/science/article/pii/S0029549325008696',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1304632',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Nuclear Infrastructure', 'Real Options', 'Risk', 'Decarbonization']
  },
  {
    slug: 'framing-risk-landscape-space-economy-trends',
    type: 'journal',
    year: 2026,
    title: 'Framing the dynamics of risk landscape amidst space economy trends',
    authors: ['Paolo Trucco', 'Alessandro Paravano', 'Giorgio Locatelli'],
    venue: 'Acta Astronautica',
    details: 'Vol. 238, Part A · pp. 332–340',
    doi: '10.1016/j.actaastro.2025.06.067',
    publisherUrl: 'https://www.sciencedirect.com/science/article/pii/S0094576525004199',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1297755',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Space Economy', 'Risk Management', 'Space Infrastructure', 'Resilience']
  },
  {
    slug: 'planning-complex-projects-for-value-creation',
    type: 'journal',
    year: 2026,
    title: 'Planning Complex Projects for Value Creation: A Discussion Guide for Decision Makers',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'IEEE Engineering Management Review',
    details: 'Vol. 54, No. 4 · August 2026 · online 2025',
    doi: '10.1109/EMR.2025.3628802',
    publisherUrl: 'https://ieeexplore.ieee.org/abstract/document/11225865',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1303910',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Complex Projects', 'Project Value', 'Systems Thinking', 'Project Governance']
  },
  {
    slug: 'drivers-barriers-resilience-projects-space-economy',
    type: 'journal',
    year: 2025,
    title: 'Drivers and Barriers in Shaping Resilience Projects: An Investigation in the Space Economy',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'IEEE Transactions on Engineering Management',
    details: 'Vol. 72 · pp. 2783–2797',
    doi: '10.1109/TEM.2025.3568298',
    publisherUrl: null,
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1297756',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Resilience Projects', 'Space Economy', 'Project Shaping', 'Risk']
  },
  {
    slug: 'projects-benefit-realisation-through-sustainable-innovation',
    type: 'journal',
    year: 2025,
    title: 'Projects benefit realisation through sustainable innovation: drivers and challenges',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'Management Decision',
    details: '2025 · pp. 1–26',
    doi: '10.1108/MD-08-2024-1751',
    publisherUrl: null,
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1297759',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Sustainable Innovation', 'Project Benefits', 'Project Ecologies', 'Space Economy']
  },
  {
    slug: 'toward-the-leo-economy-commercial-space-stations',
    type: 'journal',
    year: 2025,
    title: 'Toward the LEO economy: A value assessment of commercial space stations for space and non-space users',
    authors: ['Alessandro Paravano', 'Brendan Rosseau', 'Giorgio Locatelli', 'Mathew Weinzierl', 'Paolo Trucco'],
    venue: 'Acta Astronautica',
    details: 'Vol. 228 · pp. 453–473',
    doi: '10.1016/j.actaastro.2024.11.060',
    publisherUrl: 'https://www.sciencedirect.com/science/article/pii/S0094576524007306',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1293789',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['LEO Economy', 'Commercial Space Stations', 'Value', 'End Users']
  },
  {
    slug: 'evolving-governance-legacy-space-new-space',
    type: 'journal',
    year: 2024,
    title: 'Evolving governance in the space sector: From Legacy Space to New Space models',
    authors: ['Valentina Zancan', 'Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'Acta Astronautica',
    details: 'Vol. 225 · pp. 515–523',
    doi: '10.1016/j.actaastro.2024.09.005',
    publisherUrl: null,
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1277689',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Space Program Governance', 'New Space', 'Public–Private Partnerships', 'Artemis']
  },
  {
    slug: 'creating-claiming-social-value-science-driven-capital-projects',
    type: 'journal',
    year: 2024,
    title: 'Creating and claiming social value by joining the governance of science-driven capital projects: an investigation in the New Space Economy',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'IEEE Engineering Management Review',
    details: 'Online 2024 · final issue Vol. 53, No. 4, 2025',
    doi: '10.1109/EMR.2024.3428327',
    publisherUrl: null,
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1277688',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Social Value', 'Project Governance', 'International Space Station', 'New Space Economy']
  },
  {
    slug: 'impact-new-space-economy-on-sustainability',
    type: 'journal',
    year: 2024,
    title: 'The impact of the new space economy on sustainability: an overview',
    authors: ['Alessandro Paravano', 'Marco Patrizi', 'Emanuele Razzano', 'Giorgio Locatelli', 'Francesco Feliciani', 'Paolo Trucco'],
    venue: 'Acta Astronautica',
    details: 'Vol. 222 · pp. 162–173',
    doi: '10.1016/j.actaastro.2024.05.046',
    publisherUrl: 'https://www.sciencedirect.com/science/article/pii/S009457652400300X',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1277687',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Space Economy', 'Sustainability', 'Satellite Applications', 'SDGs']
  },
  {
    slug: 'end-users-engagement-enacting-value-complex-projects',
    type: 'journal',
    year: 2024,
    title: 'End-Users Engagement for Enacting Value of Complex Projects: An Ecological Perspective',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'Journal of Management in Engineering',
    details: 'Vol. 40, No. 3 · pp. 1–15',
    doi: '10.1061/JMENEA.MEENG-5724',
    publisherUrl: 'https://ascelibrary.org/doi/abs/10.1061/JMENEA.MEENG-5724',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1277690',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Project Ecologies', 'End-User Engagement', 'Value', 'Complex Projects']
  },
  {
    slug: 'what-is-value-new-space-economy',
    type: 'journal',
    year: 2023,
    title: 'What is value in the New Space Economy? The end-users’ perspective on satellite data and solutions',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'Acta Astronautica',
    details: 'Vol. 210 · pp. 554–563',
    volume: '210',
    firstPage: '554',
    lastPage: '563',
    publicationDate: '2023-05-05',
    issn: '0094-5765',
    publisherName: 'Elsevier on behalf of the International Academy of Astronautics',
    doi: '10.1016/j.actaastro.2023.05.001',
    publisherUrl: 'https://www.sciencedirect.com/science/article/pii/S0094576523002242',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1249723',
    repositoryLabel: 'Open access',
    fullPage: true,
    themes: ['Space Economy', 'Satellite Applications', 'End Users', 'Value'],
    takeaway: 'End-users see substantial potential in satellite data, but its value is enacted much more readily in tactical decisions than in strategic ones.',
    about: 'This study examines how organizations outside the space sector perceive and capture value from satellite data and satellite-based solutions. Focusing on the European New Space Economy, it distinguishes between expected value — what users believe satellite data could deliver — and enacted value — what they actually obtain through adoption. The research shows that the gap between the two is especially important when satellite data moves from low-risk operational uses toward strategic decisions about services and products.',
    researchQuestions: [
      'What value do end-users expect from satellite data in the New Space Economy ecosystem, and why?',
      'What is the level of adoption — or enacted value — of satellite data in end-users’ decision-making, and why?'
    ],
    approach: 'The study uses a qualitative and abductive research design. It draws on 21 manager interviews across Insurance & Finance, Energy & Utilities, and Transportation & Logistics in the European New Space Economy, complemented by internal documents, public sources, and ongoing involvement for triangulation. Value Theory provides the main theoretical lens.',
    findings: [
      'End-users generally report high expected value from satellite data, but adoption is concentrated in tactical rather than strategic decisions.',
      'Satellite data is enacted most consistently in decisions about internal activities; the gap between expected and enacted value is larger for services and especially products.',
      'Strategic adoption is constrained by transaction costs, limited satellite-data literacy and competencies, dependence on existing resources, and uncertainty about long-term value.'
    ],
    whyItMatters: 'The paper establishes an end-user perspective on value mechanisms in the New Space Economy. For research, it applies Value Theory to explain how expected and enacted value diverge in an emerging technology ecosystem. For space agencies and policymakers, the findings point to literacy and capability building as adoption levers. For satellite-data providers, they suggest that helping users develop competencies and translating technical capabilities into concrete user needs can be as important as improving the data itself.',
    citation: 'Paravano, A., Locatelli, G., & Trucco, P. (2023). What is value in the New Space Economy? The end-users’ perspective on satellite data and solutions. Acta Astronautica, 210, 554–563. https://doi.org/10.1016/j.actaastro.2023.05.001',
    related: [
      'end-users-engagement-enacting-value-complex-projects',
      'toward-the-leo-economy-commercial-space-stations',
      'value-mechanisms-satellite-infrastructure-new-space-economy'
    ],
    officialKeywords: ['Value management', 'Economic value', 'Social value', 'Environmental value', 'SDGs', 'ESG']
  },
  {
    slug: 'yes-construction-cost-time-scope-infrastructure-success',
    type: 'journal',
    year: 2023,
    title: 'Yes, construction cost, time and scope are important, but there is more: a new action plan for infrastructure success',
    authors: ['Giorgio Locatelli', 'Alessandro Paravano', 'Marco Terenzi', 'Paolo Trucco'],
    venue: 'Management Decision',
    details: 'Vol. 61, No. 13 · pp. 413–424',
    doi: '10.1108/MD-04-2022-0516',
    publisherUrl: 'https://doi.org/10.1108/MD-04-2022-0516',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1257458',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Infrastructure Success', 'Project Management', 'Social Value', 'Sustainability']
  },

  /* Books, chapters and reports */
  {
    slug: 'impacts-satellite-applications-un-sdgs',
    type: 'chapter',
    year: 2026,
    title: 'Impacts of Satellite-based Applications on the UN’s Sustainable Development Goals',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'The Oxford Handbook of the New Space Economy',
    details: 'Oxford University Press · pp. 604–626',
    doi: '10.1093/oxfordhb/9780198881049.013.0039',
    publisherUrl: 'https://academic.oup.com/edited-volume/62208/chapter-abstract/550154455',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1310297',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Satellite Applications', 'SDGs', 'Earth Observation', 'GNSS', 'Satcom']
  },
  {
    slug: 'net-zero-infrastructure-co2-taxonomy-power-plants',
    type: 'chapter',
    year: 2026,
    title: 'Towards a Net-Zero Infrastructure: A CO₂-Based Taxonomy for Power Plants',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Alessandra Neri', 'Enrico Cagno'],
    venue: 'Advances in Sustainable Energy Systems, Storage, and Conservation',
    details: 'Springer Nature · pp. 521–526',
    doi: '10.1007/978-3-031-98997-1',
    publisherUrl: 'https://link.springer.com/book/10.1007/978-3-031-98997-1?page=4',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1310292',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Net-Zero Infrastructure', 'Power Plants', 'Risk', 'CO₂']
  },
  {
    slug: 'net-zero-infrastructure-enhanced-lca-power-plants',
    type: 'chapter',
    year: 2026,
    title: 'Towards a Net-Zero Infrastructure: Proposal for an Enhanced LCA Model for Power Plants',
    authors: ['Giorgio Locatelli', 'Alessandro Paravano', 'Alessandra Neri', 'Enrico Cagno'],
    venue: 'Advances in Sustainable Energy Systems, Storage, and Conservation',
    details: 'Springer Nature · pp. 533–538',
    doi: '10.1007/978-3-031-98997-1',
    publisherUrl: 'https://link.springer.com/book/10.1007/978-3-031-98997-1?page=4',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1310294',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Life Cycle Assessment', 'Power Plants', 'Net Zero', 'Infrastructure']
  },
  {
    slug: 'commercial-deployment-nuclear-hydrogen-roadmap',
    type: 'report',
    year: 2025,
    title: 'Developing a Roadmap for the Commercial Deployment of Nuclear Hydrogen Production',
    authors: ['Alessandro Paravano et al.'],
    venue: 'IAEA Nuclear Energy Series No. NR-G-4.1',
    details: 'International Atomic Energy Agency · 180 pp.',
    doi: '10.61092/iaea.qp5y-yn4t',
    publisherUrl: 'https://www.iaea.org/publications/15633/developing-a-roadmap-for-the-commercial-deployment-of-nuclear-hydrogen-production',
    repositoryUrl: null,
    repositoryLabel: null,
    fullPage: false,
    themes: ['Nuclear Hydrogen', 'Infrastructure Roadmaps', 'Commercial Deployment', 'Energy']
  },
  {
    slug: 'value-mechanisms-satellite-infrastructure-new-space-economy',
    type: 'chapter',
    year: 2024,
    title: 'Value mechanisms of satellite infrastructure in the “new space” economy',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'The Economics of Space Sustainability',
    details: 'OECD Publishing · pp. 93–107',
    doi: '10.1787/a729c640-en',
    publisherUrl: 'https://www.oecd.org/en/publications/the-economics-of-space-sustainability_b2257346-en/full-report/component-10.html',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1278571',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Space Economy', 'Satellite Infrastructure', 'End Users', 'Value']
  },
  {
    slug: 'evolution-space-programs-governance',
    type: 'chapter',
    year: 2023,
    title: 'Evolution of space programs governance',
    authors: ['Alessandro Paravano', 'Giorgio Locatelli', 'Paolo Trucco'],
    venue: 'Research Handbook on the Governance of Projects',
    details: 'Edward Elgar Publishing · pp. 411–428',
    doi: '10.4337/9781802208078.00043',
    publisherUrl: 'https://www.elgaronline.com/doi/10.4337/9781802208078.00043',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1257456',
    repositoryLabel: 'Open access',
    fullPage: false,
    themes: ['Space Program Governance', 'New Space', 'Governance Models', 'Commercial Space']
  },

  /* Editorials */
  {
    slug: 'industry-5-project-management-special-issue',
    type: 'editorial',
    year: 2026,
    title: 'Special Issue: Expanding Research Opportunities for Project Management Researchers from Industry 5.0’s Pillars',
    authors: ['A. Romero-Torres', 'S. Sankaran', 'C. Marnewick', 'Alessandro Paravano', 'N. Johnson', 'T. Blomquist'],
    venue: 'Project Management Journal',
    details: 'Vol. 57, No. 2 · pp. 143–154',
    doi: '10.1177/87569728261420386',
    publisherUrl: 'https://journals.sagepub.com/doi/10.1177/87569728261420386',
    repositoryUrl: 'https://re.public.polimi.it/handle/11311/1310300',
    repositoryLabel: 'Repository',
    fullPage: false,
    themes: ['Industry 5.0', 'Project Management', 'Digitalization', 'Research Agenda']
  }
];

export const journalArticles = publications.filter((item) => item.type === 'journal');
export const booksAndChapters = publications.filter((item) => ['chapter', 'report'].includes(item.type));
export const editorials = publications.filter((item) => item.type === 'editorial');

export function getPublication(slug) {
  return publications.find((item) => item.slug === slug);
}

export function getDetailedPublications() {
  return publications.filter((item) => item.fullPage);
}
